const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const vm=require('node:vm');
const ID='11111111-1111-4111-8111-111111111111';
function load(head){const source=fs.readFileSync(path.join(__dirname,'..','pages','api','checkout.js'),'utf8').replace("import {head} from '@vercel/blob';","const {head}=blob;").replace("import {getSavedPreview,getSavedPreviewByShare} from '../../lib/saved-previews';","const {getSavedPreview,getSavedPreviewByShare}=saved;").replace('export default async function handler','async function handler').replace(/\n}\s*$/,'\n}\nmodule.exports={verifiedPreview,handler};');const context={module:{exports:{}},process:{env:{BLOB_READ_WRITE_TOKEN:'token'}},Promise,Array,Number,RegExp,String,URLSearchParams,blob:{head},saved:{getSavedPreview:async()=>({mcsJobId:ID}),getSavedPreviewByShare:async()=>null}};vm.runInNewContext(source,context);return context.module.exports.verifiedPreview;}
test('checkout validates every Blob asset required by paid continuation with no provider call',async()=>{const seen=[];const verify=load(async pathname=>{seen.push(pathname);if(pathname.includes('reference'))return{contentType:'image/jpeg',size:100};if(pathname.includes('scene-image'))return{contentType:'image/png',size:100};if(pathname.includes('storybook'))return{contentType:'application/pdf',size:2000};if(pathname.includes('narration')||pathname.includes('sound-effect'))return{contentType:'audio/mpeg',size:100};return{contentType:'video/mp4',size:600000};});await verify(ID);assert.equal(seen.length,27);assert.ok(seen.includes(`mcs/jobs/${ID}/preview-movie.bin`));for(let n=1;n<=6;n++)for(const kind of ['scene-image','narration','sound-effect','scene-video'])assert.ok(seen.includes(`mcs/jobs/${ID}/${kind}-${n}.bin`));});
test('checkout rejects a missing continuation asset before payment',async()=>{const verify=load(async pathname=>{if(pathname.endsWith('scene-video-6.bin'))throw new Error('missing');return{contentType:pathname.includes('reference')?'image/jpeg':pathname.includes('scene-image')?'image/png':pathname.includes('narration')||pathname.includes('sound-effect')?'audio/mpeg':pathname.includes('storybook')?'application/pdf':'video/mp4',size:600000};});await assert.rejects(()=>verify(ID),/missing/);});
