import {useState} from 'react';
export default function Create(){
  const[idea,setIdea]=useState('');const[plan,setPlan]=useState('');const[status,setStatus]=useState('');const[image,setImage]=useState('');const[moods,setMoods]=useState([]);const[busy,setBusy]=useState(false);
  const toggle=m=>setMoods(x=>x.includes(m)?x.filter(v=>v!==m):[...x,m]);
  async function stage(){
    if(!idea.trim()){setStatus('Tell Stage the story idea first.');return}
    setBusy(true);setStatus('Stage is shaping your 3-minute movie…');
    try{const r=await fetch('/api/stage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea,moods})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Stage failed');setPlan(j.plan);setStatus('Your full 3-minute story is ready. Edit anything you want, then make the free opening minute.')}catch(e){setStatus(e.message)}finally{setBusy(false)}
  }
  async function file(e){const f=e.target.files?.[0];if(!f)return;if(f.size>12*1024*1024){setStatus('Please choose a photo smaller than 12 MB.');return}const reader=new FileReader();reader.onload=()=>setImage(reader.result);reader.readAsDataURL(f)}
  async function preview(){if(!image){setStatus('Add one clear photo first.');return}if(!plan){setStatus('Build your story with Stage first.');return}setBusy(true);setStatus('Turning your story into a cinematic 18-scene screenplay, then starting the free opening minute…');try{const r=await fetch('/api/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,image,moods})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Preview failed');location.href='/preview?jobId='+encodeURIComponent(j.jobId)+'&mcsJobId='+encodeURIComponent(j.mcsJobId)}catch(e){setStatus(e.message);setBusy(false)}}
  return <main style={{minHeight:'100vh',background:'#120f18',color:'#fff',fontFamily:'Arial,sans-serif'}}><div style={{maxWidth:980,margin:'0 auto',padding:20}}><header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><a href='/' style={{color:'#fff'}}>← Main Character Studios by Tiffani</a><a href='/my-orders' style={{color:'#fff',fontWeight:900}}>My Orders</a></header><div style={{marginTop:26,padding:'10px 14px',display:'inline-flex',gap:12,alignItems:'center',borderRadius:999,background:'#24182f',border:'1px solid #5c4470'}}><span>3-minute movie</span><strong>$49</strong></div><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(40px,7vw,70px)',marginBottom:8}}>Make them the main character.</h1><p style={{fontSize:18,opacity:.85}}>AI Story Chat included · 3-minute personalized moving movie · first 60 seconds free</p><section style={{marginTop:24,background:'#19121f',border:'1px solid #3d2d49',borderRadius:24,padding:20}}><div style={{display:'flex',gap:12,alignItems:'center',marginBottom:14}}><div style={{width:42,height:42,borderRadius:99,background:'#7b2cff',display:'grid',placeItems:'center',fontWeight:900}}>AI</div><div><b>STAGE · LIVE AI STORY CHAT · INCLUDED</b><div style={{opacity:.7}}>Tell it anything. Rough notes and half-formed ideas are fine.</div></div></div><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder='Type your story here…' style={{width:'100%',minHeight:150,padding:15,borderRadius:16,background:'#0f0b13',color:'#fff',boxSizing:'border-box',fontSize:16}}/><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'14px 0'}}>{['funny','dramatic','scary','sci-fi','fantasy','dark humor'].map(m=><button type='button' key={m} onClick={()=>toggle(m)} style={{padding:'9px 13px',borderRadius:999,background:moods.includes(m)?'#7b2cff':'#2b2135',color:'#fff',border:'1px solid #5c4470'}}>{m}</button>)}</div><div style={{margin:'18px 0'}}><label style={{display:'block',fontWeight:800,marginBottom:8}}>Add the person, people, or pet starring in the movie</label><input type='file' accept='image/*' onChange={file}/>{image&&<span style={{marginLeft:10}}>✓ photo ready</span>}</div><button disabled={busy} onClick={stage} style={{padding:'13px 20px',borderRadius:999,fontWeight:900}}>{busy?'Working…':'Action! Build my story'}</button><p style={{minHeight:24}}>{status}</p>{plan&&<><h3>Your complete editable 3-minute plan</h3><textarea value={plan} onChange={e=>setPlan(e.target.value)} style={{width:'100%',minHeight:360,padding:14,borderRadius:16,background:'#0f0b13',color:'#fff',boxSizing:'border-box'}}/><p style={{opacity:.72}}>Scenes 1–6 become your free opening minute. After payment, the same story continues with scenes 7–18.</p><button disabled={busy} onClick={preview} style={{marginTop:8,padding:'15px 22px',borderRadius:999,fontWeight:900}}>Preview my story for free →</button></>}</section></div></main>
}