import {useState} from 'react';
export default function Create(){
  const[idea,setIdea]=useState('');const[plan,setPlan]=useState('');const[status,setStatus]=useState('');const[image,setImage]=useState('');const[moods,setMoods]=useState([]);const[busy,setBusy]=useState(false);
  const toggle=m=>setMoods(x=>x.includes(m)?x.filter(v=>v!==m):[...x,m]);
  async function stage(){
    if(!idea.trim()){setStatus('Tell Stage the story idea first.');return}
    if(!moods.length){setStatus('Choose at least one mood.');return}
    setBusy(true);setStatus('Stage is writing your movie plan…');
    try{const r=await fetch('/api/stage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea,moods})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Stage failed');setPlan(j.plan);setStatus('Plan ready — edit anything you want, then create the preview.')}catch(e){setStatus(e.message)}finally{setBusy(false)}
  }
  async function file(e){const f=e.target.files?.[0];if(!f)return;if(f.size>12*1024*1024){setStatus('Please choose a photo smaller than 12 MB.');return}const reader=new FileReader();reader.onload=()=>setImage(reader.result);reader.readAsDataURL(f)}
  async function preview(){
    if(!image){setStatus('Add one clear photo first.');return}if(!plan){setStatus('Create the story plan first.');return}
    setBusy(true);setStatus('Starting your 60-second moving preview…');
    try{const r=await fetch('/api/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,image})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Preview failed');location.href='/preview?jobId='+encodeURIComponent(j.jobId)+'&mcsJobId='+encodeURIComponent(j.mcsJobId)}catch(e){setStatus(e.message);setBusy(false)}
  }
  return <main style={{minHeight:'100vh',background:'#120f18',color:'#fff',fontFamily:'Arial,sans-serif'}}><div style={{maxWidth:900,margin:'0 auto',padding:20}}><a href='/' style={{color:'#fff'}}>← Main Character Studios by Tiffani</a><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(38px,7vw,68px)'}}>Make them the main character.</h1><p>5-minute personalized moving movie · $79 · first 60 seconds preview free</p><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder='Tell Stage your story idea…' style={{width:'100%',minHeight:150,padding:14,borderRadius:16,background:'#17111e',color:'#fff',boxSizing:'border-box'}}/><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'12px 0'}}>{['funny','dramatic','scary','sci-fi','fantasy','dark humor'].map(m=><button type='button' key={m} onClick={()=>toggle(m)} style={{padding:'10px 14px',borderRadius:999,background:moods.includes(m)?'#7b2cff':'#2b2135',color:'#fff',border:'1px solid #5c4470'}}>{m}</button>)}</div><div style={{margin:'18px 0'}}><label style={{display:'block',fontWeight:800,marginBottom:8}}>Add one clear photo</label><input type='file' accept='image/*' onChange={file}/>{image&&<span style={{marginLeft:10}}>✓ photo ready</span>}</div><button disabled={busy} onClick={stage} style={{padding:'12px 18px',borderRadius:999,fontWeight:900}}>{busy?'Working…':'Action! Build my story'}</button><p style={{minHeight:24}}>{status}</p>{plan&&<><h3>Your editable movie plan</h3><textarea value={plan} onChange={e=>setPlan(e.target.value)} style={{width:'100%',minHeight:360,padding:14,borderRadius:16,background:'#17111e',color:'#fff',boxSizing:'border-box'}}/><button disabled={busy} onClick={preview} style={{marginTop:12,padding:'14px 20px',borderRadius:999,fontWeight:900}}>Create my free moving preview →</button></>}</div></main>
}